# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W3aDxSY0pC3EQ_4LmCiufjWTFygXVZ49
"""


# Then import and download 'punkt'
import nltk
nltk.download('punkt')
# Download 'punkt_tab' as well for sentence tokenization
nltk.download('punkt_tab')
from nltk.tokenize import sent_tokenize
import re

sample_text = """
IN THE SUPREME COURT OF INDIA

CIVIL APPELLATE JURISDICTION

CIVIL APPEAL NO. 1234 OF 2020

ABC Corporation Ltd. ...Appellant

Vs.

XYZ Enterprises Pvt. Ltd. ...Respondent

JUDGMENT

This appeal arises out of the judgment dated 10th March 2020 passed by the High Court. The High Court held that the agreement between the parties was valid and enforceable. The appellant challenged the same, arguing that the contract was void due to lack of consideration. After hearing both sides, this Court holds that the agreement was valid, and the appeal is accordingly dismissed.
"""

def preprocess(text):
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r'\d+', '', text)
    return sent_tokenize(text)

sentences = preprocess(sample_text)
print("\n--- Tokenized Sentences ---\n")
for s in sentences:
    print(s)



from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.text_rank import TextRankSummarizer

def extractive_summary(text, ):
    parser = PlaintextParser.from_string(text, Tokenizer("english"))
    summarizer = TextRankSummarizer()
    summary = summarizer(parser.document, )
    return ' '.join(str(sentence) for sentence in summary)

# Example usage
if __name__ == "__main__":
    sample_text = """IN THE HIGH COURT OF DELHI AT NEW DELHI

CIVIL WRIT PETITION NO. 9876 OF 2021

ABC Developers Pvt. Ltd. ...Petitioner

Versus

Union of India & Others ...Respondents

JUDGMENT

The petitioner challenged the cancellation of an allotment made by the Delhi Development Authority (DDA) on the grounds that due procedure was not followed. The counsel for the petitioner contended that no prior notice or opportunity to be heard was provided before the cancellation, thereby violating principles of natural justice.

On the other hand, the respondent DDA argued that the allotment was obtained by misrepresentation of facts and that the cancellation was made in accordance with the applicable rules and policies.

After examining the evidence and hearing both sides, this Court finds that the cancellation was made without giving the petitioner a fair chance to respond. The principles of natural justice were clearly not adhered to.

Accordingly, the cancellation order dated 12th July 2021 is set aside. The DDA is directed to issue a fresh notice and allow the petitioner to present their case before taking any further action.
"""
    print("\n--- Extractive Summary ---\n")
    print(extractive_summary(sample_text))


